---
title: "indole + vs tnaA bacteria touch responses"
author: "Julia Balch"
date: "2023-04-16"
output: html_document
---
Plot comparing anterior touch on indole vs tnaA bacteria

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(viridis)
library(patchwork)
library(ggsignif)
theme_set(theme_classic())

Figure_name <- "Figure2d"

```


```{r message = FALSE}

csv_path <- "C:/Users/julia/OneDrive/Desktop/Projects/JBIndoleTouchResponseMS/datasets/TouchResponsesData.csv"

TouchResponses <- read_csv(csv_path) %>%
     mutate(date = as.Date(date, format = "%m/%d/%Y"))

dataframe <-TouchResponses %>%
  subset(food  %in% c('OP50', "OPtnaA", "K12 tnaA", "BW25113") & is.na(additive) & !time_off_food_min %in% c("10", "0", "30") 
         & genotype %in% c("N2", "cest-1.2"))

dataframe$genotype <- factor(dataframe$genotype, levels = c("N2", "cest-1.2"),
                             ordered = TRUE)
dataframe$food <- factor(dataframe$food, levels = c("OP50", "OPtnaA", "BW25113", "K12 tnaA"),
                             ordered = TRUE)

```


```{r message = FALSE}
plot <- dataframe %>%
  
    ggplot(aes(x = genotype, y = bends, fill = genotype)) +
    stat_summary(aes(fill= genotype),
                 geom = "bar", 
                 fun = "mean", 
                 width = 0.6,
                 alpha = 0.7) +
    stat_summary(geom = "errorbar", 
                 fun.data = "mean_se", 
                 width = 0.1) +
  scale_fill_manual(values = c("N2" = "#797282",
                               ##  "#582878",
                               "cest-1.2" = "#26828e")) +
  labs(y = "Body Bends per Reversal (n)")+
  geom_signif(comparisons = list(c("N2", "cest-1.2")),
              map_signif_level = TRUE, tip_length = 0, y_position = 4) +
  theme(axis.text.x=element_text(size=12, face="italic", color = "black"), 
        axis.text.y=element_text(size=12, color = "black"), 
        axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 0), size = 12)) +
  facet_grid(. ~ food)  +
  scale_y_continuous(expand = expansion(mult = c(0, .1)))
  
plot
```

```{r saving}

### make a folder
new_folder <- fs::dir_create('../figures/',Figure_name)

## save the plot
ggsave(plot,
       file = file.path(new_folder,
                 Figure_name,
                 paste0(Figure_name,'.png')))

## save the formatted edited tibble:
write_csv(dataframe,
          file = file.path(new_folder,
                 Figure_name,
                 paste0(Figure_name,'.csv')))

```
